jubatus/core/anomaly/light_lof.cpp

fix issue #92 
`anomaly::set_row` should not `touch()` neighbors of updated ID. 
It touching neighbors means that `unlearner` delete IDs out of order of registration.
it is counter-intuitive behavior.

anomaly unlearner should delete ID in order of registration

---

jubatus/core/table/column/abstract_column.hpp
jubatus/core/table/column/abstract_column_test.cpp

Nearest Neighbor set a row for an incorrect id when it tries to overwrite the row of existing ids.
This patch fixes the bug.

fix index of update_at_ function

---

jubatus/core/fv_converter/datum_to_fv_converter_test.cpp

init_weight_manager() does almost same as datum_to_fv_converter's default constructor.

Remove an unnecessary function in test.

---

jubatus/core/classifier/wscript
jubatus/core/storage/wscript

I want to use jubatus_core as a library.
[suma/ruby-jubatus](https://github.com/suma/ruby-jubatus) uses jubatus_core class directly,  it needs each internal class definition of C++ headers.
Is it necessary to public many headers If jubatus_core project hope to be used as a library?
Of course, internal API and header definition can be changed by version up, but I think library versioning can avoid bad API use. I give up API compatibility major version up still in rapid development of jubatus_core.

Add classifiers headers to install headers

---

jubatus/core/clustering/clustering_test.cpp
jubatus/core/clustering/gmm.cpp
jubatus/core/clustering/kmeans_compressor.cpp
jubatus/core/driver/clustering_test.cpp

Originally reported by Hiroshi Kuwajima's [post](https://groups.google.com/d/msg/jubatus/J8dDkXKj7JE/S8hE2HbM0v0J) 
There are devide-by-zero and log(0) calculation exists.
It appears values with limited distribution(like integer).
For first aid, it should use very small value instead of zero.
Some radical(or mathematical) solution will be needed further.

Clustering sometimes gets NaN

---

jubatus/core/fv_converter/converter_config.cpp

User sometimes suffer `unknown type:` error.
It doesn't include config file's erroneous position or full name of specified name of type(it is sometimes zero-length string).
So error message should include type name of erroneous configuration.

fv_converter error should be more verbose

---

jubatus/core/bandit/bandit_factory.cpp
jubatus/core/bandit/bandit_factory_test.cpp
jubatus/core/bandit/epsilon_greedy.cpp
jubatus/core/bandit/epsilon_greedy.hpp
jubatus/core/bandit/exp3.cpp
jubatus/core/bandit/exp3.hpp
jubatus/core/bandit/softmax.cpp
jubatus/core/bandit/softmax.hpp
jubatus/core/bandit/summation_storage.cpp
jubatus/core/bandit/summation_storage.hpp
jubatus/core/bandit/summation_storage_test.cpp
jubatus/core/bandit/ucb1.cpp
jubatus/core/bandit/ucb1.hpp
jubatus/core/driver/bandit_test.cpp

related issue: https://github.com/jubatus/jubatus_core/issues/125
This pull request adds `assume_unrewarded` parameter to each bandit algorithms.
When `assume_unrewarded` is `true`, reward is assumed to zero on calling `select_arm`,
and you don't have to call `register_reward` when reward was actually zero.

Add assume_unrewarded option to bandit

---

jubatus/core/storage/bit_vector.hpp

Improved bit_vector. This request contains:
- Use __builtin_popcount for optimization.
- Remove unused code.
I wrote this patch based on the basis of @unnonouno's work.
The original work contains more optimization, so I will send a request later.
This patch runs fast when SSE 4.2 is enabled.
GCC enables SSE 4.2 with -msse4.2.

Improve bit_vector.

---

jubatus/core/recommender/euclid_lsh.cpp
jubatus/core/recommender/euclid_lsh.hpp

fix #98 
Caching of random vector generation may be good for improving performance.
But cache control needs exclusive access control.
It depends on how calculation is heavy.

retain projection was not used

---

jubatus/core/storage/bit_vector.hpp
wscript

Fixed code and wscript for cpplint. It seems impossible to purge direct use of (unsigned) long (long), so I made `./waf cpplint` to ignore them.

Fix code and wscript for cpplint.

---

jubatus/core/clustering/kmeans_clustering_method.cpp

Fixes https://github.com/jubatus/jubatus_core/issues/150.

Fix kmeans to throw exception in get_nearest_center when clustering is not performed

---

jubatus/core/classifier/linear_classifier.cpp
jubatus/core/driver/classifier.cpp
jubatus/core/fv_converter/counter.hpp
jubatus/core/fv_converter/keyword_weights.cpp
jubatus/core/fv_converter/keyword_weights.hpp
jubatus/core/fv_converter/weight_manager.cpp
jubatus/core/fv_converter/weight_manager.hpp
jubatus/core/storage/local_storage_mixture.cpp
jubatus/core/unlearner/lru_unlearner.cpp
jubatus/core/unlearner/lru_unlearner.hpp
jubatus/core/unlearner/random_unlearner.cpp
jubatus/core/unlearner/random_unlearner.hpp
jubatus/core/unlearner/unlearner_base.hpp
jubatus/core/unlearner/unlearner_base_test.cpp

We added the following values to get_status of classifier.
* unlearner
* random_unlearner
* ``num_unlearner_ids``: The number of IDs that have stored
* lru_unlearner
* ``num_unlearner_unlearned_ids``: The number of IDs that have stored (exclude sticky_ids)
* ``num_unlearner_sticky_ids``: The number of sticky IDs that have stored
* weight_manager
* ``weight_manager_version``: The version number of weight_manager
* ``master_document_count``: The number of documents that have stored in master area
* ``diff_document_count``: The number of documents that have stored in diff area
* ``master_num_document_frequencies``: The number of features that have stored in master area
* ``diff_num_document_frequencies``: The number of features that have stored in diff area
* ``master_num_weights``: The …

Improve get status of classifier

---

jubatus/core/common/jsonconfig/config.hpp
jubatus/core/recommender/recommender_factory.cpp

Refs https://github.com/jubatus/jubatus_core/pull/120
Current develop branch does not accept inverted_index config without "parameter" block.  To keep backward compatibility this issue must be addressed before release.

[develop] fix recommender to accept inverted_index config without parameter block

---

jubatus/core/clustering/storage.cpp
jubatus/core/clustering/storage.hpp

Fix #70; now clustering MIX works properly.
Each clustering instance (in jubatus_core layer) have its own identifier to distinguish itself in cluster.  The ID is generated and assigned by jubatus_server layer in format of "IP_PORT" (e.g., ``10.0.0.1_9199``.)
(Note: see https://github.com/jubatus/jubatus/pull/1041 for ID generation spec.)
In the clustering instance, however, the ID is marked to be serialized (i.e., [listed in MSGPACK_DEFINE](https://github.com/jubatus/jubatus_core/blob/0.2.1/jubatus/core/clustering/storage.hpp#L64)).  After a model recovery phase (which always runs when new server joins to an existing cluster), an ID of the first instance in the cluster will be copied over to the newly-joined instance.  As a result, every instance in the cluster will have the same ID.  By …

fix clustering storage to exclude name from serialization (fix #70)

---

jubatus/core/clustering/clustering_config.hpp
jubatus/core/clustering/clustering_method_factory.cpp
jubatus/core/clustering/gmm.cpp
jubatus/core/clustering/gmm.hpp
jubatus/core/clustering/gmm_clustering_method.cpp
jubatus/core/clustering/gmm_clustering_method.hpp
jubatus/core/clustering/gmm_test.cpp
jubatus/core/clustering/kmeans_clustering_method.cpp
jubatus/core/clustering/kmeans_clustering_method.hpp
jubatus/core/clustering/kmeans_compressor.cpp

Exposes a seed of clustering as a configuration parameter; fix #176.
This patch adds new configuration parameter `seed` (uint32_t) which is used as a seed in mtrand.

fix clustering interface to accept externally specified seed (fix #176)

---

jubatus/core/anomaly/anomaly_base.hpp
jubatus/core/anomaly/anomaly_base_test.cpp
jubatus/core/anomaly/light_lof.cpp
jubatus/core/anomaly/light_lof.hpp
jubatus/core/anomaly/light_lof_test.cpp
jubatus/core/anomaly/lof.cpp
jubatus/core/anomaly/lof.hpp
jubatus/core/driver/anomaly.cpp

This patch implements the idea proposed in #130.
When `ignore_kth_same_point` (which is a optional configuration defaults to false) is specified as true, nearest neighbor search runs before actually adding the data. If the distance to the (k-1) th neighbor is 0 (which means model already has (k-1) points that have the same feature vector as the data being added), reject adding new data to avoid LRD to go inf.
Note: we need to document this once this gets merged.

Implement ignore_kth_same_point option to light_lof (fix #130)

---

jubatus/core/storage/bit_vector.hpp

Fixes #191.
I did a simple micro benchmark for this patch for 3 times.
I saw roughly 2x speed up for empty bit_vector and 33x for non-empty bit_vector.
https://github.com/kmaehashi/sandbox/blob/master/jubatus/bit_vector_performance/test.cpp
Before applying this patch:
```
empty vector: took 60000
non-empty vector: took 3690000
empty vector: took 50000
non-empty vector: took 3710000
empty vector: took 50000
non-empty vector: took 3690000
```
After applying this patch:
```
empty vector: took 30000
non-empty vector: took 110000
empty vector: took 30000
non-empty vector: took 110000
empty vector: took 30000
non-empty vector: took 110000
```

Improve bit_vector::is_empty performance (fix #191)

---

jubatus/core/storage/bit_vector.hpp

Fixes #192.
I did a simple micro benchmark for this patch for 3 times.
I saw a slight improvements for non-empty bit_vector.
Although #193 made `is_empty` much faster, taking the fact that almost every vectors being not empty in Jubatus use cases into consideration, it is still meaningful to apply this patch, as the benchmark result shows.
https://github.com/kmaehashi/sandbox/blob/master/jubatus/bit_vector_performance/test_hamming.cpp
As of v0.2.3:
```
empty vector: took 20000
non-empty vector: took 1570000
empty vector: took 10000
non-empty vector: took 1570000
empty vector: took 20000
non-empty vector: took 1570000
```
After applying #193:
```
empty vector: took 10000
non-empty vector: took 490000
empty vector: took 10000
non-empty vector: took 490000
empty vector: took 10000
non-empty …
```

remove unnecessary bit_vector::is_empty call (fix #192)

---

jubatus/core/storage/bit_vector.hpp
jubatus/core/storage/bit_vector_test.cpp

This PR fixes various bugs (as follows) in bit_vector.  Please note that these bugs do NOT affect the Jubatus functionality, however they may cause unit test failures. It may also become a issue for developers reusing bit_vector in their original Jubatus engine.
* Fixed illegal out-of-bound array access in `is_empty` and `bit_count` methods. This only occurs when the length of bit_vector is 0-bit.  The similar loop condition in `calc_hamming_distance` method is also fixed for performance. This fixes `bit_index_storage_test` test failures (that was observed under 32-bit environment.)
* Fixed bounds checking of `pos` (bit position) argument in `clear_bit`, `set_bit` and `get_bit` methods. Tests are added for these edge cases. Related to #170.
* Fixed signature of `resize_and_clear` method …

Fix bit vector bug

---

jubatus/core/nearest_neighbor/bit_vector_nearest_neighbor_base.cpp
jubatus/core/nearest_neighbor/nearest_neighbor_base.cpp
jubatus/core/storage/column_table.cpp
jubatus/core/storage/column_table.hpp

Fix #199.
As pthread mutexes are reentrant and acquisition of read locks are blocked when acquisition of write lock is being blocked, for two threads T1 and T2:
1. T1 tries to acquire read lock => success
2. T2 tries to acquire write lock => blocked (wait for the lock 1. to be released)
3. T1 tries to acquire read lock (again, before releasing 1.) => blocked (wait for the lock 2. to be acquired & released)
... so T1 and T2 deadlocks.
When deadlocked, you'll see that two threads are stuck in this way:
```
(gdb) info threads
Id   Target Id         Frame
4    Thread 0x7feefc4f5700 (LWP 20293) "jubanearest_nei" do_sigwait (set=<optimized out>, sig=0x7feefc4f4df8) at ../nptl/sysdeps/unix/sysv/linux/../../../../../sysdeps/unix/sysv/linux/sigwait.c:65
3    Thread 0x7feefbcf4700 (LWP 20294) …
```

fix double acquisition of read lock (fix #199)

---

jubatus/core/anomaly/light_lof.cpp
jubatus/core/anomaly/light_lof_test.cpp

Previously jubaanomaly run with config that does not define ``ignore_kth_same_point`` parameter cause SegV on calling ``set`` RPC.
This patch fixes the problem.

fix null checking of ignore_kth_same_point in anomaly

---

jubatus/core/graph/graph_wo_index.cpp

When calling `remove_node` for nodes that have edge(s), `jubagraph` currently returns an error message that says `graph_wo_index::remove_node unknown id=X`. This is wrong.

fix error message in graph::remove_node

---

jubatus/core/driver/recommender_test.cpp
jubatus/core/recommender/lsh.cpp
jubatus/core/recommender/lsh.hpp
jubatus/core/recommender/lsh_test.cpp
jubatus/core/storage/bit_index_storage.cpp
jubatus/core/storage/bit_index_storage.hpp
jubatus/core/storage/bit_index_storage_test.cpp

fix #189 
~~This PR is work in progress.~~
~~The remaining tasks are followings:~~

Add unlearner to lsh

---

jubatus/core/storage/bit_index_storage.cpp
jubatus/core/storage/bit_index_storage_test.cpp

This PR fixes the issue reported in #211.
Prior to this fix, analyze methods of `bit_index_storage` (used by LSH / MinHash algorithms of recommender) did not work until next MIX if rows are erased by `clear_row`
I also improved several comments.

Fix bit_index_storage to ignore 0-bit vector in analyze methods

---

jubatus/core/bandit/arm_info.hpp
jubatus/core/bandit/bandit_base.hpp
jubatus/core/bandit/summation_storage.cpp
jubatus/core/bandit/summation_storage.hpp
jubatus/core/bandit/summation_storage_test.cpp
jubatus/core/bandit/ucb1.cpp

This pull request fixes #186.
I have added total_trial_count to summation_storage to cache the summation of trial_count of all arms.
UCB1 method can use this value to reduce calculation cost.

Improve ucb1

---

jubatus/core/recommender/inverted_index.hpp
jubatus/core/recommender/inverted_index_euclid.cpp
jubatus/core/recommender/inverted_index_euclid.hpp
jubatus/core/recommender/recommender.hpp
jubatus/core/recommender/recommender_factory.cpp
jubatus/core/recommender/wscript
jubatus/core/storage/inverted_index_storage.cpp
jubatus/core/storage/inverted_index_storage.hpp
jubatus/core/storage/inverted_index_storage_test.cpp

I added a new method for recommender that calculates similarities based on exact euclidean distance.
This method is mainly expected to be used in conjunction with anomaly LOF.

implement inverted_index_euclid recommender method

---

jubatus/core/storage/inverted_index_storage.cpp
jubatus/core/storage/inverted_index_storage_test.cpp

This bug was introduced in #127.
Rows removed by `clear_row` was not ignored when calculating Euclidean distance in inverted_index.

(develop) fix inverted_index_storage::calc_euclid_scores to ignore remove row

---

.travis.yml

Enables build, unittest, cpplint tests in below distributions
* CentOS6 + gcc 4.4
* CentOS7 + gcc 4.8
* CentOS7 + gcc 5.2 (devtoolset-4)
* Ubuntu 12.04 + gcc 4.6
* Ubuntu 14.04 + gcc 4.8
* Ubuntu 16.04 + gcc 5.3
gcc4.8 enables to test #254
gcc5.x enables to test #246 #250

Improves travis-ci config to support ubuntu/centos+gcc, cpplint

---

jubatus/core/anomaly/light_lof_test.cpp
jubatus/core/nearest_neighbor/avx_mathfunc.hpp
jubatus/core/nearest_neighbor/lsh_function.cpp
jubatus/core/nearest_neighbor/sse_mathfunc.hpp
jubatus/util/math/random.h
jubatus/util/math/random/sfmt.h
jubatus/util/math/random_test.cpp
jubatus/util/math/wscript
wscript

NNで利用するrandom_projectionをSSE2/AVX2により高速化しました．
過去のバージョンが作成するモデルとの互換性がなくなっている他，
精度にも影響を与える変更を加えています．
最終的には以下のように10倍以上高速になりました．
* iris: 3.49319 => 0.214638 [ms/train]
* dorothea: 782.344 => 37.9593 [ms/train]
* 20news: 145.126 => 7.2572 [ms/train]
各コミットの補足です．
1. 正規分布の浮動小数点型を倍精度から単精度に変更しました．
random_projectionでは符号しか利用しないため，単精度にしても精度に与える影響は少ないと考えています． (詳細はコミットメッセージのaccuracyを参照ください)
2. SSE2/AVX2を用いて一度に8個/16個の正規分布に基づく乱数を生成するようにしました
3. 乱数生成器をMT19937からSFMT607にしました．MT19937はスループットは良いのですが状態が大きく初期化が重いため，random_projectionのように特徴量毎に初期化する必要がある場合は状態が少ない607程度で良いようです．またxorshift128+のように更に状態が少ないものも有りますがこちらはスループットが良くないので，MT/SFMTの各周期，xorshift128+を評価した結果もっとも性能が良かったSFMT607を採用しました．
related issue: #244

optimized random_projection

---

.travis.yml

#246 is affected by this ubuntu bug https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1568899

Temporary disabled Ubuntu 16.04 tests in the TravisCI

---

jubatus/core/classifier/nearest_neighbor_classifier.cpp

I found that unlearner does not work in MIX when using NN-based classifier.
This patch will solve the above problem.

Add unlearner to mixable_versioned_table in NN-based classifier

---

jubatus/core/common/thread_pool.cpp
jubatus/core/common/thread_pool.hpp
jubatus/core/common/wscript
jubatus/core/nearest_neighbor/bit_vector_nearest_neighbor_base.cpp
jubatus/core/nearest_neighbor/bit_vector_nearest_neighbor_base.hpp
jubatus/core/nearest_neighbor/bit_vector_ranking.cpp
jubatus/core/nearest_neighbor/bit_vector_ranking.hpp
jubatus/core/nearest_neighbor/euclid_lsh.cpp
jubatus/core/nearest_neighbor/euclid_lsh.hpp
jubatus/core/nearest_neighbor/lsh.cpp
jubatus/core/nearest_neighbor/lsh.hpp
jubatus/core/nearest_neighbor/lsh_function.cpp
jubatus/core/nearest_neighbor/lsh_function.hpp
jubatus/core/nearest_neighbor/minhash.cpp
jubatus/core/nearest_neighbor/minhash.hpp
jubatus/core/storage/abstract_column.hpp
jubatus/core/storage/bit_vector.cpp
jubatus/core/storage/bit_vector.hpp
jubatus/core/storage/fixed_size_heap.hpp
jubatus/core/storage/wscript
jubatus/util/concurrent/thread.cpp
jubatus/util/concurrent/thread.h

This pull request is based from non-merged branch.
based branch: #250 + #254
related issue: #244 
更新履歴
* 2016/03/23: 初版
* 2016/04/04: C++11の機能を使わずにマルチスレッド探索を実行できるようにしました
何点か議論するポイントがあります．
1. 各スレッドに割り当てる最低のデータサイズ(searchの場合は点の数，random_projectionの場合は特徴量の数)を定めるかどうか．定める場合コンフィグにすべきか定数にすべきか．(現在はデータサイズは気にせずにスレッド数で等分割しています)
2. searchとrandom_projectionの並列数は異なるコンフィグとすべきか (現在は同じコンフィグを共用しています)
3. スレッドプールの最大サイズを，threads にあわせるべきか (現在は実行した環境の論理コア数を上限としています)
また，今回 threads というオプションパラメータを追加しましたが，これはモデルに依存するパラメータというより，実行環境に依存するパラメータです．将来的にはこのパラメータはモデルに保存せずに，モデルロード時に指定するコンフィグで指定する値を利用するようにしたほうが良いと思っています．

NN parallel search/random_projection implementation

---

jubatus/util/concurrent/thread.h

FreeBSD 10.3Rにgcc48をインストールしてビルドしてみたところint64_tのエラーがでていたので、sys/types.hをincludeしました。おそらくここに入れるのはあまり良くないような気もするので、適当なところ教えてもらえればそちらに移します。

add include sys/types.h because of int64_t error on FreeBSD 10.3R

---

jubatus/core/nearest_neighbor/euclid_lsh.cpp

This fixes #253: distance between two points that are very close to each other cannot be calculated properly in some cases.
In this PR, I fixed the code to directly calculate the distance between two points if the hamming distance, which is a result of Cosine LSH, is 0 (i.e., cosine similarity of two points are 1.0).
This is a technique already used in Euclid LSH of Recommender.  https://github.com/jubatus/jubatus_core/blob/0.3.0/jubatus/core/storage/lsh_index_storage.cpp#L98

improve NN euclid_lsh calculation accuracy when hamming distance is zero (fix #253)

---

tools/codestyle/run_cpplint.sh

Now `./waf cpplint` checks include guard.
Refs https://github.com/jubatus/jubatus/pull/1119

add include guard check to run_cpplit (core)

---

jubatus/core/storage/inverted_index_storage.cpp
jubatus/core/storage/inverted_index_storage.hpp

This fixes #251: distance between two same points cannot be calculated properly in some cases.
In this PR, I eliminated the redundant calculation, e.g., replacing `sqrt(x) * sqrt(x)` with `x`, to avoid unnecessary dropping float precision.

Improve Recommender inverted_index/inverted_index_euclid calculation accuracy between same data points

---

jubatus/core/nearest_neighbor/euclid_lsh.cpp

I found the code that may cause deadlock in ``euclid_lsh``.
See. https://github.com/jubatus/jubatus_core/issues/199

Fix deadlock in euclid_lsh

---

jubatus/core/fv_converter/char_splitter.cpp
jubatus/core/fv_converter/char_splitter.hpp
jubatus/core/fv_converter/char_splitter_test.cpp

modified char_splitter to support UTF-8 (implements #299) 

---

wscript

This fix was needed in jubatus_core too. https://github.com/jubatus/jubatus/pull/1136, https://github.com/jubatus/jubatus/issues/910

disable _GLIBCXX_DEBUG when configured with --enable-debug

---

jubatus/core/classifier/nearest_neighbor_classifier.cpp
jubatus/core/storage/column_table.hpp

I found the code that may cause deadlock in `nearest_neighbor_classifier`.
* ``train`` using ``unlearner``
* ``touch`` is called in ``column_table::set_row`` (called from ``push`` RPC). In ``set_row``, ``column_table`` acquire the lock. So, ``touch`` must not get the lock.
* ``regenerate_labels``
* ``scoped_rlock`` is acquired in ``regenerate_labels``. But ``get_key_nolock`` and ``size_nolock`` are not used in this scope.
In addition, I reconsider the exclusive control in ``delete_label``.
* Calling ``table->get_key()`` many times is very heavy operation. So, I changed the way of exclusive control.

Fix deadlock in NN-Classifier

---

jubatus/core/common/exception.cpp
jubatus/core/common/exception.hpp
jubatus/core/common/exception_info.hpp
jubatus/core/common/exception_test.cpp

Supporse you have an invalid configuration file:
```json
{
"method" : 123,
"foo": 123
}
```
When running server with such config file, the server now displays error messages in format that is much easier to understand ...
```
$ jubaclassifier -f test.json
2016-08-23 12:10:23,034 11518 FATAL [server_util.hpp:146] exception in main thread: jubatus::core::common::config_exception: invalid configuration
(#0) Message: "foo" is not used ()
(#0) Message: String is expected, but Integer is given. (.method)
(#0) Message: "converter" is not found ()
(#0) Source: ../jubatus/server/server/../../server/framework/server_helper.hpp
(#0) Line: 100
(#0) Function: jubatus::server::framework::server_helper<Server>::server_helper(const jubatus::server::framework::server_argv&, bool) [with Server = …
```

Improve configuration error message

---

jubatus/core/clustering/clustering.cpp
jubatus/core/clustering/clustering_test.cpp
jubatus/core/clustering/storage_factory.cpp
jubatus/core/clustering/storage_factory.hpp
jubatus/core/clustering/storage_test.cpp

fix #314
if compressor_method is simple, bucket_length, compressed_bucket_size,bicriteria_base_size,forgetting_factor,forgetting_threshold are ignored.
In addtion, modify bucket_size range
modify bucket_size range from 2<=bucket_size to 1<=bucket_size.
(This PR includes revert commit for develop, master branch)

refactoring parameter check on clustering feature (includes revert commit)

---

jubatus/core/clustering/clustering_test.cpp
jubatus/core/clustering/mixable_model_test.cpp
jubatus/core/clustering/model_gmm_test.cpp
jubatus/core/clustering/model_test.cpp
jubatus/core/clustering/storage_factory.cpp
jubatus/core/clustering/storage_test.cpp
jubatus/core/clustering/types.hpp
jubatus/core/driver/clustering.cpp
jubatus/core/driver/clustering.hpp
jubatus/core/driver/clustering_test.cpp

fix #317 
refactoring clustering API  below.
```
indexed_point 
0: string  ID,
1: datum point
```
ID indentify indivisual data. 
```
weighted_index
0: double weight
1: string ID
```
```
bool push(0: list<indexed_point> points)
```
```
list<list<weighted_index>> get_core_members_light()
list<list<weighted_index>> get_nearest_members_light()
```
This API returns only IDs and Weights. It is easy to know which data includes cluster.
And change config value
```
change compressor_ method value from {compressive_kmeans,compressive_gmm} to {compressive}.
Because we can tell kmeans and gmm with method value.
```

Refactoring Clustering API and config value

---

jubatus/core/recommender/inverted_index.cpp
jubatus/core/storage/inverted_index_storage.cpp
jubatus/core/storage/inverted_index_storage.hpp
jubatus/core/storage/inverted_index_storage_test.cpp

Fixes https://github.com/jubatus/jubatus/issues/682.
This PR adds ``mark_column_removed`` API to ``storage::inverted_index_storage``.
Callers trying to remove the entire column (currently ``recommender::inverted_index`` only) must call it after removing all records that belongs to the column.
This PR also removes ``void remove_row(const std::string& row);``, which is declared in the header but not actually implemented.

fix inverted_index to rows cleared by clear_row correctly removed

---

jubatus/core/clustering/clustering.cpp
jubatus/core/clustering/clustering_config.hpp
jubatus/core/clustering/clustering_method_factory.cpp
jubatus/core/clustering/clustering_test.cpp
jubatus/core/clustering/dbscan.cpp
jubatus/core/clustering/dbscan.hpp
jubatus/core/clustering/dbscan_clustering_method.cpp
jubatus/core/clustering/dbscan_clustering_method.hpp
jubatus/core/clustering/dbscan_test.cpp
jubatus/core/clustering/storage_factory.cpp
jubatus/core/clustering/types.hpp
jubatus/core/clustering/wscript
jubatus/core/driver/clustering.cpp
jubatus/core/driver/clustering.hpp
jubatus/core/driver/clustering_test.cpp

fix #330 
add dbscan algorithm for jubaclustering.
dbscan algorithm has two parameter eps and min_core_point.
It does not need k parameter, because it does not calculate center point of the cluster.
This algorithm does not support (throw unsupported_method exception)
- get_k_center
- get_nearest_center
- get_nearest_members_light

add dbscan algorithm for clustering.

---

jubatus/core/fv_converter/datum_to_fv_converter.cpp
jubatus/core/fv_converter/datum_to_fv_converter_test.cpp

Currently, binary feature converter doesn't have any way to add rule name to the feature-key.
This pull-request modifies the method like other converters.

fix convert binaries to pass the feature rule name

---

jubatus/core/storage/local_storage_mixture.cpp

I have renamed a field name of get_status (`diff_size` to `num_features_diff`) because I think `num_features_diff` is clearer.

rename getstatus diff_size to num_features_diff

---

jubatus/util/concurrent/rwmutex.cpp
wscript

This PR introduces new compile-time flag called `JUBATUS_UTIL_CONCURRENT_RWMUTEX_ERRORCHECK`.
The flag is enabled by default when configured with `--enable-debug`.
When this flag is specified, each rwmutex class keep track of thread IDs that owns its read lock.
It raises assertion if the thread that already owns read lock tries to take a read/write lock.
So this enables sanity check to detect double acquision of a read lock of pthread_rwlock in the same thread.
This feature is intended to detect bugs seen in #199, #200, #303 etc.

add rwmutex sanity check to debug build

---

jubatus/core/anomaly/lof_storage.cpp

In ``lof`` algorithm of Anomaly engine, when config is set to:
1. "ignore_kth_same_point": true  => behaves as `true`
2. "ignore_kth_same_point": false  => behaves as `true`, which is not expected
3. "ignore_kth_same_point" is not defined => behaves as `false`
This PR fixes the case 2.

fix ignore_kth_same_point_ cannot be set to false

---

.travis.yml
wscript

depends: #345
This is #281 reproduce test.
Currently, CentOS7 + devtoolset-4 fails caused by #281.

Add shared library loading test

---

.travis.yml
wscript

depends: #345 #346 
FMV有効時にいくつかの環境に置いてdlopen時にSEGVするのを回避するために
ld.bfd の代わりに ld.gold を利用するようにしました．
gcc6以降(Ubuntu 16.10)はbfdでも問題ない様なのでFMV有効かつgcc6未満を対称にしてます

Use gold linker instead of bfd to avoid FMV dynamic loading issues

---

jubatus/core/driver/regression_test.cpp
jubatus/core/regression/cosine_similarity_regression.cpp
jubatus/core/regression/cosine_similarity_regression.hpp
jubatus/core/regression/euclidean_distance_regression.cpp
jubatus/core/regression/euclidean_distance_regression.hpp
jubatus/core/regression/inverted_index_regression.cpp
jubatus/core/regression/inverted_index_regression.hpp
jubatus/core/regression/nearest_neighbor_regression.cpp
jubatus/core/regression/nearest_neighbor_regression.hpp
jubatus/core/regression/regression_factory.cpp
jubatus/core/regression/regression_factory_test.cpp

This PR implements #351.
The `weight` parameter is optional and this PR implements only `distance` weight option.
If `uniform`or other weight is set, it behaves the same way as the previous version.
I checked the behavior of the distance option using this code.
https://gist.github.com/shiodat/e0920ebc299320a6e1630175a38e0bab
The config file changes as follows:
```
{
"method": "NN",
"parameter": {
"method": "euclid_lsh",
"nearest_neighbor_num": 8,
"weight": "distance",  #new parameter(optional)
"parameter": {
"hash_num": 512
}
}
}
```

Add distance weight option to nn regression

---

jubatus/core/clustering/clustering_factory_test.cpp

https://github.com/jubatus/jubatus_core/pull/362 causes unit test to fail when running
```
./waf configure --disable-eigen
./waf build --checkall
```
This PR fixes the problem by disabling GMM test when Eigen is unavailable.

skip gmm test if JUBATUS_USE_EIGEN is undefined

---

jubatus/util/system/sysstat.cpp

Dear,
I suggest modify function from `atoi` to `strtoull`.
Because  I think `strtoull` is safer than `atoi`.
For example, when data model of LLP64 or LP64, size of return value of `atoi` is 32bit(-2147483648 - +2147483647).
(Because type of return value of `atoi` is int).
And unit of "MemFree" and "Cashed" are "kb".So, the maximum that can be converted size are about 2TB with `atoi`.
Memory size of many 64bit system is over 2TB.So, `atoi` have maybe occurred over flow when a computer have over 2TB memory.
When `atoi` occurred over flow, action of `atoi` is undefined.
So, I think suggest use `strtoull` instead `atoi`.

Improve process of convert string to number.

---

jubatus/util/lang/enable_shared_from_this.h
jubatus/util/lang/function.h
jubatus/util/lang/ref.h
jubatus/util/lang/shared_ptr.h
jubatus/util/lang/weak_ptr.h

> https://gcc.gnu.org/gcc-6/changes.html
> The default mode for C++ is now -std=gnu++14 instead of -std=gnu++98
Fixed #368

Fix compile error in gcc-6.0 and above

---

wscript

This PR fixes wscript to test if ld.gold exists.
Refs https://github.com/jubatus/jubatus_core/pull/347

check if ld.gold is available

---

jubatus/core/bandit/bandit_factory.cpp
jubatus/core/bandit/bandit_factory_test.cpp
jubatus/core/bandit/epsilon_decreasing.cpp
jubatus/core/bandit/epsilon_decreasing.hpp
jubatus/core/bandit/wscript

(ref : #354 )
Add epsilon decreasing algorithm referring to GreedyMix algorithm in [ref](https://pdfs.semanticscholar.org/2c50/eccfb2878cc7e4286791f582f96c52a26da9.pdf).
From the reference, epsilon is updated by following equation.
Here is the result table of slot machine experiment based on the [Jubatus example](https://github.com/jubatus/jubatus-example) 
You can see the experiment detail [here](https://gist.github.com/imaimai1125/e8352f680415311509fe1306006b81b7)
|Algorithm|Parameter|Ave. of reward|Selection Rate of optimal arm|
|---|---|---|---|
|epsilon-decreasing|0.5|46020|**0.707**|
|epsilon-decreasing|0.7|**46443**|**0.689**|
|epsilon-decreasing|1.0|**46163**|0.630|
|epilon-greedy|0.01|35392|0.155|
|epilon-greedy|0.1|44819|0.587|
|epilon-greedy|0.3|45169|0.614| …

add epsilon decreasing algorithm

---

jubatus/core/anomaly/light_lof.cpp
jubatus/core/anomaly/lof.cpp
jubatus/core/classifier/linear_classifier.cpp
jubatus/core/classifier/nearest_neighbor_classifier.cpp
jubatus/core/classifier/nearest_neighbor_classifier.hpp
jubatus/core/common/unordered_set.hpp
jubatus/core/common/wscript
jubatus/core/driver/nearest_neighbor.cpp
jubatus/core/recommender/euclid_lsh.cpp
jubatus/core/recommender/inverted_index.cpp
jubatus/core/recommender/lsh.cpp
jubatus/core/recommender/minhash.cpp
jubatus/core/recommender/nearest_neighbor_recommender.cpp
jubatus/core/regression/nearest_neighbor_regression.cpp
jubatus/core/unlearner/lru_unlearner.cpp
jubatus/core/unlearner/lru_unlearner.hpp
jubatus/core/unlearner/lru_unlearner_test.cpp
jubatus/core/unlearner/random_unlearner.cpp
jubatus/core/unlearner/random_unlearner.hpp
jubatus/core/unlearner/random_unlearner_test.cpp
jubatus/core/unlearner/unlearner_base.hpp
jubatus/core/unlearner/unlearner_base_test.cpp

Fixes https://github.com/jubatus/jubatus_core/issues/389
I implemented ``pack`` and ``unpack`` interface to ``unlearner``.
And, I implemented this method call to algorithms:
I tested this patch using [this](https://github.com/rimms/misc/tree/master/jubatus_core-389) .
Note that nearest_neighbor does not support `unlearner`. But `driver::nearest_neighbor` has the [interface](https://github.com/jubatus/jubatus_core/blob/master/jubatus/core/driver/nearest_neighbor.hpp#L53) using `unlearner`. I think this method will not be called from anywhere.

Support save/load of unlearner

---

jubatus/core/driver/recommender_test.cpp

I tried to confirm the situation of #275.
But, all algorithm returns empty list when id is not registered. (#275 is already fixed.)
I wrote tests for this case.

Add tests of missing id

---

jubatus/core/storage/bit_vector.cpp

Dear, developers.
I've fixed bit_vector for suppressing below warning.
`warning: comparison between signed and unsigned integer expressions [-Wsign-compare]`

Fix bit_vector for suppressing warning
