jubatus/jubatus_core

jubatus/core/clustering/gmm.cpp
jubatus/core/clustering/gmm_test.cpp

Fix gmm to throw exception in get_nearest_center when points are not added

---

jubatus/core/driver/nearest_neighbor.cpp
jubatus/core/driver/nearest_neighbor.hpp
jubatus/core/driver/nearest_neighbor_test.cpp

implement get_all_rows API in NN driver (refs #58)

---

jubatus/core/anomaly/wscript
jubatus/core/burst/wscript
jubatus/core/classifier/wscript
jubatus/core/clustering/wscript
jubatus/core/common/jsonconfig/wscript
jubatus/core/common/wscript
jubatus/core/driver/wscript
jubatus/core/framework/wscript
jubatus/core/fv_converter/wscript
jubatus/core/graph/wscript
jubatus/core/recommender/wscript
jubatus/core/regression/wscript
jubatus/core/stat/wscript
jubatus/core/third_party/wscript
jubatus/core/unlearner/wscript
jubatus/core/wscript
jubatus/util/concurrent/wscript
jubatus/util/data/wscript
jubatus/util/lang/algorithm/wscript
jubatus/util/lang/wscript
jubatus/util/math/wscript
jubatus/util/system/wscript
jubatus/util/text/wscript
jubatus/util/wscript
jubatus/wscript

https://github.com/jubatus/jubatus/issues/924

Add "# -*- python -*-" to wscripts for eamcs.

---

jubatus/core/fv_converter/datum_to_fv_converter_test.cpp

Remove an unused typedef.

---

jubatus/core/clustering/gmm_test.cpp

http://stackoverflow.com/questions/2777541/static-const-double-in-c

Move an initialization to correct location.

---

jubatus/core/anomaly/light_lof.cpp

remove unused table constructor

---

jubatus/core/table/column/column_table.hpp

fix typo s/colum_id/column_id/g fix #97

---

jubatus/core/anomaly/lof_storage.cpp

This just improves the readability of the code.

add comment to lof_storage.cpp

---

jubatus/core/common/jsonconfig_test.cpp
jubatus/core/common/key_manager_test.cpp
jubatus/core/driver/anomaly_test.cpp
jubatus/core/driver/clustering_test.cpp
jubatus/core/framework/mixable_versioned_table.cpp
jubatus/core/fv_converter/mixable_weight_manager_test.cpp
jubatus/core/graph/graph_wo_index.cpp
jubatus/core/nearest_neighbor/bit_vector_nearest_neighbor_base_test.cpp
jubatus/util/text/json_test.cpp

Reduce warnings.

---

jubatus/core/classifier/arow.cpp
jubatus/core/classifier/confidence_weighted.cpp
jubatus/core/classifier/linear_classifier.cpp
jubatus/core/classifier/nearest_neighbor_classifier.cpp
jubatus/core/classifier/nearest_neighbor_classifier.hpp
jubatus/core/classifier/normal_herd.cpp
jubatus/core/common/key_manager.cpp
jubatus/core/common/key_manager.hpp
jubatus/core/driver/classifier.hpp
jubatus/core/driver/classifier_test.cpp
jubatus/core/driver/test_util.hpp
jubatus/core/framework/linear_function_mixer_test.cpp
jubatus/core/fv_converter/weight_manager.cpp
jubatus/core/fv_converter/weight_manager.hpp
jubatus/core/nearest_neighbor/bit_vector_nearest_neighbor_base.cpp
jubatus/core/storage/column_table.hpp
jubatus/core/storage/local_storage.cpp
jubatus/core/storage/local_storage.hpp
jubatus/core/storage/local_storage_mixture.cpp
jubatus/core/storage/local_storage_mixture.hpp
jubatus/core/storage/storage_base.hpp
jubatus/core/storage/storage_test.cpp
unittest_gtest.py

make classifier thread safe

---

jubatus/core/common/jsonconfig/cast.hpp

fix warnings of harmless uninitialized value (fix #132)

---

jubatus/core/fv_converter/datum_to_fv_converter.cpp
jubatus/core/fv_converter/datum_to_fv_converter_test.cpp

fix combination feature crash on empty sfv_t (fix #146)

---

jubatus/core/bandit/epsilon_greedy.cpp
jubatus/core/bandit/exp3.cpp
jubatus/core/bandit/softmax.cpp
jubatus/core/bandit/ucb1.cpp

``get_arm_info(const std::string& arm_id)`` is wrong.
I changed to ``get_arm_info(const std::string& player_id)``.
See https://github.com/jubatus/jubatus/blob/0.7.1/jubatus/server/server/bandit.idl#L69

Rename arm_id to player_id

---

jubatus/core/bandit/summation_storage.cpp
jubatus/core/bandit/summation_storage_test.cpp

related issue: https://github.com/jubatus/jubatus_core/issues/138

Throw exception when arm_id is not registered

---

jubatus/core/bandit/summation_storage.cpp

https://github.com/jubatus/jubatus_core/issues/142

Fix bandit::summation_storage::clear

---

jubatus/core/wscript

add plugin.hpp for installation (fix #139)

---

jubatus/core/anomaly/lof.cpp
jubatus/core/anomaly/lof_test.cpp

related issue: https://github.com/jubatus/jubatus/issues/588

Implement overwrite to lof

---

jubatus/core/driver/nearest_neighbor_test.cpp
jubatus/core/framework/mixable_versioned_table.cpp
jubatus/core/framework/mixable_versioned_table.hpp
jubatus/core/storage/column_table.hpp

`column_table` should touch the row when jubatus mixes table. fix #100

touch rows on push pull mix fix #100

---

jubatus/core/driver/classifier_test.cpp
jubatus/core/storage/local_storage_mixture.cpp

add missing locks and tests as @kmaehashi [said](https://github.com/jubatus/jubatus/issues/968#issuecomment-92681250)

add missing locks in local_storage_mixture

---

jubatus/core/fv_converter/combination_feature.hpp
jubatus/core/fv_converter/combination_feature_impl.hpp
jubatus/core/fv_converter/datum_to_fv_converter.cpp
jubatus/core/fv_converter/datum_to_fv_converter_test.cpp

support non-commutative functions in combination feature

---

jubatus/core/driver/clustering_test.cpp
jubatus/core/driver/nearest_neighbor_test.cpp
jubatus/core/fv_converter/revert_test.cpp
jubatus/util/text/json_test.cpp

Eliminate warnings.

---

jubatus/core/bandit/ucb1.cpp

fix ucb1 trial_count increment

---

jubatus/core/bandit/exp3.cpp

fix exp3 calculations

---

jubatus/core/driver/recommender_test.cpp
jubatus/core/recommender/inverted_index.cpp
jubatus/core/recommender/inverted_index.hpp
jubatus/core/recommender/recommender_factory.cpp
jubatus/core/storage/inverted_index_storage.cpp
jubatus/core/storage/inverted_index_storage.hpp
jubatus/core/storage/sparse_matrix_storage.hpp
jubatus/core/unlearner/lru_unlearner.cpp

`inverted_index` is tend to consume memory, there is big benefit for supporting `unlearner` in inverted index. fix #51

implemented unleaning feature in inverted_index

---

jubatus/core/bandit/exp3.cpp

fix exp3 gamma parameter range (fix #163)

---

jubatus/core/storage/bit_vector.hpp

`pos == bit_num_` is invalid condition.

Fix argument check in bit_vector::set_bit().

---

jubatus/core/clustering/util.cpp
jubatus/core/clustering/util_test.cpp
jubatus/core/clustering/wscript

Add some tests for missing module.

add tests for clustering utils

---

jubatus/core/clustering/discrete_distribution.cpp
jubatus/core/clustering/discrete_distribution.hpp
jubatus/core/clustering/gmm.cpp
jubatus/core/clustering/gmm.hpp
jubatus/core/clustering/gmm_test.cpp
jubatus/core/clustering/kmeans_clustering_method.cpp
jubatus/core/clustering/kmeans_clustering_method.hpp
jubatus/core/clustering/kmeans_compressor.cpp
jubatus/core/clustering/kmeans_compressor.hpp

fix mtrand used in clustering to use fixed seed value (fix #167)

---

jubatus/core/driver/clustering_test.cpp

~~Note: this patch depends on #172.  I'll rebase this patch once #172 got merged.~~
* Rebased clustering driver test improvement (#129) by kumagi to the latest develop branch
* Revised the test conditions.

Fix clustering test

---

jubatus/core/anomaly/lof.cpp
jubatus/core/anomaly/lof.hpp
jubatus/core/driver/classifier_test.cpp

Just eliminated unused things, and some code cleanup.

remove unused headers and using clauses

---

jubatus/core/driver/classifier_test.cpp
jubatus/core/storage/local_storage_mixture.cpp

Add missing lock in local_storage_mixture::inp

---

jubatus/core/anomaly/light_lof.cpp
jubatus/core/classifier/linear_classifier.cpp
jubatus/core/classifier/nearest_neighbor_classifier.cpp
jubatus/core/recommender/inverted_index.cpp
jubatus/core/recommender/nearest_neighbor_recommender.cpp

improve unlearner overflow error message (fix #178)

---

jubatus/core/nearest_neighbor/bit_vector_nearest_neighbor_base.cpp
jubatus/core/nearest_neighbor/nearest_neighbor_base.cpp
jubatus/core/storage/bit_vector.hpp
jubatus/core/storage/column_table.hpp
wscript

Resubmitting #188 (wscript modified to remove ``-msse4.2`` option)

improve nearest_neighbor performance and remove bugs

---

jubatus/core/classifier/arow.cpp
jubatus/core/classifier/confidence_weighted.cpp
jubatus/core/classifier/linear_classifier.cpp
jubatus/core/classifier/normal_herd.cpp
jubatus/core/framework/linear_function_mixer_test.cpp
jubatus/core/storage/local_storage.cpp
jubatus/core/storage/local_storage.hpp
jubatus/core/storage/local_storage_mixture.cpp
jubatus/core/storage/local_storage_mixture.hpp
jubatus/core/storage/storage_base.hpp
jubatus/core/storage/storage_test.cpp

Use read/write lock in linear_classifier

---

jubatus/core/anomaly/lof.hpp

fix codestyle

---

jubatus/core/clustering/clustering.hpp
jubatus/core/clustering/gmm.cpp
jubatus/core/clustering/gmm_clustering_method.cpp
jubatus/core/clustering/gmm_test.cpp
jubatus/core/clustering/kmeans_clustering_method.cpp
jubatus/core/clustering/model_gmm_test.cpp
jubatus/core/clustering/model_test.cpp

Fix clustering to throw exception in get_k_center/get_core_members when clustering is not performed

---

jubatus/core/fv_converter/num_feature_factory.cpp
jubatus/core/fv_converter/num_filter_factory.cpp
jubatus/core/fv_converter/num_filter_factory_test.cpp
jubatus/core/fv_converter/num_filter_impl.hpp
jubatus/core/storage/bit_vector.hpp

Fix typos (refs: https://github.com/jubatus/jubatus/issues/1068)

fix typo in messages

---

jubatus/core/anomaly/anomaly_base.hpp
jubatus/core/anomaly/anomaly_base_test.cpp
jubatus/core/anomaly/light_lof.cpp
jubatus/core/anomaly/light_lof.hpp
jubatus/core/anomaly/lof.cpp
jubatus/core/anomaly/lof.hpp
jubatus/core/anomaly/lof_storage.cpp
jubatus/core/anomaly/lof_storage.hpp
jubatus/core/anomaly/lof_storage_test.cpp
jubatus/core/common/vector_util.cpp
jubatus/core/common/vector_util.hpp
jubatus/core/driver/anomaly.cpp

add ignore kth same point option to lof

---

jubatus/core/driver/recommender_test.cpp
jubatus/core/recommender/minhash.cpp
jubatus/core/recommender/minhash.hpp
jubatus/core/recommender/minhash_test.cpp

This patch is a part of https://github.com/jubatus/jubatus_core/issues/189

Add unlearner to minhash

---

jubatus/core/classifier/nearest_neighbor_classifier.cpp
jubatus/core/classifier/nearest_neighbor_classifier.hpp

Fixes https://github.com/jubatus/jubatus_core/issues/213

Add lock to labels_

---

jubatus/core/common/key_manager.hpp
jubatus/core/common/key_manager_test.cpp

fix key_manager::swap to swap next_id_ (fix #224)

---

jubatus/core/storage/local_storage.cpp

fix #233
This PR removed duplicated substitution

removed duplicated substitution

---

jubatus/core/fv_converter/datum_to_fv_converter.cpp
jubatus/core/fv_converter/weight_manager.cpp

fix #227 
This PR modified to follow Jubatus coding style

modified to follow Jubatus coding style

---

jubatus/core/driver/recommender_test.cpp
jubatus/core/recommender/inverted_index_euclid.cpp
jubatus/core/recommender/inverted_index_euclid.hpp
jubatus/core/recommender/recommender_factory.cpp

Add unlearner to inverted_index_euclid

---

jubatus/core/nearest_neighbor/lsh.cpp
jubatus/core/nearest_neighbor/lsh.hpp
jubatus/core/nearest_neighbor/lsh_benchmark.cpp

It works for parallel hashing.

add thread option for lsh

---

jubatus/core/bandit/bandit_factory_test.cpp
jubatus/core/bandit/ts.cpp

I have fixed cpplint erros in bandit.

fix cpplint error in bandit

---

jubatus/core/nearest_neighbor/bit_vector_ranking.cpp
jubatus/core/nearest_neighbor/euclid_lsh.cpp
jubatus/core/storage/abstract_column.hpp
jubatus/core/storage/bit_vector.cpp
jubatus/core/storage/bit_vector.hpp
jubatus/core/storage/wscript

This pull request is based from non-merged branch.
based branch: #246
related issue: #244

improve hamming distance calculation

---

jubatus/core/common/exception.hpp
jubatus/util/system/syscall.cpp
jubatus/util/system/sysstat.cpp

This is freebsd support patch. I make on FreeBSD 9.

freebsd support

---

jubatus/core/recommender/inverted_index_euclid.cpp
jubatus/core/recommender/inverted_index_euclid.hpp
jubatus/core/recommender/lsh.cpp
jubatus/core/recommender/lsh.hpp
jubatus/core/recommender/minhash.cpp
jubatus/core/recommender/minhash.hpp
jubatus/core/recommender/recommender_base.hpp
jubatus/core/storage/bit_index_storage.cpp
jubatus/core/storage/bit_index_storage.hpp

recommender: fix {lsh,minhash}::{similar,neighbor}_row_from_id to avoid using orig_

---

jubatus/core/common/jsonconfig/config.hpp
jubatus/core/driver/recommender_test.cpp
jubatus/core/recommender/euclid_lsh.cpp
jubatus/core/recommender/euclid_lsh.hpp
jubatus/core/storage/lsh_index_storage.cpp
jubatus/core/storage/lsh_index_storage.hpp
jubatus/core/storage/lsh_index_storage_test.cpp

Add unlearner to euclid_lsh

---

jubatus/core/classifier/classifier_factory.cpp
jubatus/core/classifier/cosine_similarity_classifier.cpp
jubatus/core/classifier/cosine_similarity_classifier.hpp
jubatus/core/classifier/euclidean_distance_classifier.cpp
jubatus/core/classifier/euclidean_distance_classifier.hpp
jubatus/core/classifier/inverted_index_classifier.cpp
jubatus/core/classifier/inverted_index_classifier.hpp
jubatus/core/classifier/nearest_neighbor_classifier.cpp
jubatus/core/classifier/nearest_neighbor_classifier_util.cpp
jubatus/core/classifier/nearest_neighbor_classifier_util.hpp
jubatus/core/classifier/wscript

related to #234 .
I have added classifier 2 methods using inverted index storage.
One uses cosine similarity, the other uses euclidean distance for calculating the score.
Note that current implementation doesn't support deleting label and unlearner.

add inverted index classifier

---

jubatus/core/classifier/nearest_neighbor_classifier.cpp
jubatus/core/classifier/nearest_neighbor_classifier.hpp
jubatus/core/driver/driver.cpp
jubatus/core/framework/mixable.cpp
jubatus/core/framework/mixable.hpp

Fixes #210
Note: this patch based on #270

Generate labels in MIX

---

jubatus/core/classifier/passive_aggressive.cpp

(develop) fix classifier PA missing label increment (refs #272)

---

jubatus/core/nearest_neighbor/euclid_lsh.cpp

Add exclusive lock in euclid_lsh::neighbor_row

---

jubatus/core/nearest_neighbor/euclid_lsh.cpp
jubatus/core/nearest_neighbor/euclid_lsh.hpp
jubatus/core/nearest_neighbor/lsh.cpp
jubatus/core/nearest_neighbor/lsh.hpp
jubatus/core/nearest_neighbor/lsh_function.cpp
jubatus/core/nearest_neighbor/lsh_function.hpp

This pull request is based from non-merged branch.
based branch: #260 ~~based branch: #246~~ (updated: 2016/03/28)
related issue: #244

Uses LRU to cache gaussian random number in random_projection

---

jubatus/core/driver/weight.cpp
jubatus/core/driver/weight.hpp
jubatus/core/driver/weight_test.cpp
jubatus/core/driver/wscript

This is a jubatus_core part of https://github.com/jubatus/jubatus/issues/1105

add weight driver

---

jubatus/core/anomaly/anomaly_factory.cpp
jubatus/core/anomaly/anomaly_factory_test.cpp
jubatus/core/anomaly/lof.cpp
jubatus/core/anomaly/lof.hpp
jubatus/core/anomaly/lof_storage.cpp
jubatus/core/anomaly/lof_storage.hpp
jubatus/core/anomaly/lof_storage_test.cpp

This PR adds unlearner in anomaly LOF.  Implements #231.

implement unlearner in anomaly lof (#231)

---

jubatus/core/fv_converter/converter_config.cpp
jubatus/core/fv_converter/datum_to_fv_converter.cpp
jubatus/core/fv_converter/datum_to_fv_converter.hpp
jubatus/core/fv_converter/datum_to_fv_converter_test.cpp
jubatus/core/fv_converter/key_name_utils.hpp
jubatus/core/fv_converter/keyword_weights.cpp
jubatus/core/fv_converter/keyword_weights.hpp
jubatus/core/fv_converter/keyword_weights_test.cpp
jubatus/core/fv_converter/mixable_weight_manager_test.cpp
jubatus/core/fv_converter/weight_manager.cpp
jubatus/core/fv_converter/weight_manager.hpp
jubatus/core/fv_converter/weight_manager_test.cpp

This PR implements BM25 global weighting scheme for string features as proposed in #284.

Implement BM25 global weighting scheme for string features (implements #284)

---

jubatus/core/clustering/storage.cpp
jubatus/core/driver/clustering_test.cpp

Reset revision number in clear

---

jubatus/core/fv_converter/char_splitter.cpp
jubatus/core/fv_converter/char_splitter.hpp
jubatus/core/fv_converter/char_splitter_test.cpp
jubatus/core/fv_converter/string_feature_factory.cpp
jubatus/core/fv_converter/wscript

I implemented specified character splitter.(refs #255)
And I will add another PR of website after this.

split string feature by specified separator(implements #255)

---

jubatus/core/fv_converter/converter_config.cpp
jubatus/core/fv_converter/datum_to_fv_converter.cpp
jubatus/core/fv_converter/datum_to_fv_converter.hpp
jubatus/core/fv_converter/weight_manager.cpp
jubatus/core/fv_converter/weight_manager.hpp
jubatus/core/fv_converter/weight_manager_test.cpp

Implement IDF-1 global weighting (fix #209)

---

jubatus/core/framework/mixable_versioned_table.cpp

fix #307 
I tested jubatus_core (build with ``_GLIBCXX_DEBUG``) using ``waf --checkall``.

Finish put_diff when diff object's size is empty

---

jubatus/core/driver/regression.cpp
jubatus/core/driver/regression.hpp
jubatus/core/driver/regression_test.cpp

remove unnnecessary argument in regression driver

---

jubatus/core/clustering/clustering.cpp
jubatus/core/clustering/clustering_test.cpp
jubatus/core/clustering/storage_factory.cpp
jubatus/core/clustering/storage_factory.hpp
jubatus/core/clustering/storage_test.cpp

fix #314 
if compressor_method is simple, bucket_length, compressed_bucket_size,bicriteria_base_size,forgetting_factor,forgetting_threshold are ignored.
In addtion, modify bucket_size range
modify bucket_size range from 2<=bucket_size to 1<=bucket_size.

refactoring parameter check on clustering feature.

---

jubatus/core/fv_converter/datum_to_fv_converter.cpp
jubatus/core/fv_converter/datum_to_fv_converter.hpp

remove unused function (fix #315)

---

jubatus/core/driver/graph.cpp
jubatus/core/driver/graph.hpp
jubatus/core/driver/graph_test.cpp
jubatus/core/graph/graph_wo_index.cpp
jubatus/core/graph/graph_wo_index.hpp
jubatus/core/graph/graph_wo_index_test.cpp

Fix https://github.com/jubatus/jubatus/issues/1149

add find_max_int_id to graph engine

---

jubatus/core/fv_converter/dynamic_binary_feature.cpp
jubatus/core/fv_converter/dynamic_binary_feature.hpp
jubatus/core/fv_converter/dynamic_binary_feature_test.cpp
jubatus/core/fv_converter/dynamic_combination_feature.cpp
jubatus/core/fv_converter/dynamic_combination_feature.hpp
jubatus/core/fv_converter/dynamic_loader.cpp
jubatus/core/fv_converter/dynamic_loader.hpp
jubatus/core/fv_converter/dynamic_loader_test.cpp
jubatus/core/fv_converter/dynamic_num_feature.cpp
jubatus/core/fv_converter/dynamic_num_feature.hpp
jubatus/core/fv_converter/dynamic_num_feature_test.cpp
jubatus/core/fv_converter/dynamic_num_filter.cpp
jubatus/core/fv_converter/dynamic_num_filter.hpp
jubatus/core/fv_converter/dynamic_num_filter_test.cpp
jubatus/core/fv_converter/dynamic_string_feature.cpp
jubatus/core/fv_converter/dynamic_string_feature.hpp
jubatus/core/fv_converter/dynamic_string_feature_test.cpp
jubatus/core/fv_converter/dynamic_string_filter.cpp
jubatus/core/fv_converter/dynamic_string_filter.hpp
jubatus/core/fv_converter/dynamic_string_filter_test.cpp
jubatus/core/fv_converter/so_factory.cpp
jubatus/core/fv_converter/so_factory.hpp
jubatus/core/fv_converter/so_factory_test.cpp
jubatus/core/fv_converter/test_binary_feature.cpp
jubatus/core/fv_converter/test_num_feature.cpp
jubatus/core/fv_converter/test_num_filter.cpp
jubatus/core/fv_converter/test_splitter.cpp
jubatus/core/fv_converter/test_splitter_null.cpp
jubatus/core/fv_converter/test_string_filter.cpp
jubatus/core/fv_converter/wscript

I want to use mecab plugin in embedded-jubatus !

Imports fv_converter dynamic method from jubatus server

---

jubatus/core/classifier/linear_classifier.cpp
jubatus/core/classifier/linear_classifier.hpp
jubatus/core/classifier/nearest_neighbor_classifier.cpp

Protect unlearner in Classifier

---

jubatus/core/fv_converter/dynamic_loader.cpp
wscript

Fix lacking features; refs #338

fix dynamic loader to accept relative paths and JUBATUS_PLUGIN_PATH

---

.travis.yml
wscript

Avoid link error in Ubuntu 16.04

---

jubatus/core/storage/column_table.hpp

Fixes https://github.com/jubatus/jubatus_core/issues/342

Fix double acquision of a lock in column_table

---

README.rst

Refs https://github.com/jubatus/website/issues/323

deprecate support for Ubuntu 12.04 LTS

---

README.rst

Same as [jubatus#1191](https://github.com/jubatus/jubatus/pull/1191).

add travis status

---

jubatus/core/storage/inverted_index_storage.cpp

Fix cosine similarity calculation floating-point error

---

jubatus/core/anomaly/lof_storage.cpp

fix lof score becomes inf

---

jubatus/core/storage/local_storage.hpp

Refs https://github.com/jubatus/jubatus/issues/1190

make local_storage model format compatible with local_storage_mixture

---

jubatus/core/clustering/storage_factory.cpp

Fix build error with --disable-eigen configure option

---

wscript

add _mm256_srl_epi32 to AVX2 test

---

jubatus/core/bandit/bandit_factory.cpp
jubatus/core/bandit/bandit_factory_test.cpp
jubatus/core/bandit/epsilon_greedy.cpp
jubatus/core/bandit/epsilon_greedy.hpp
jubatus/core/bandit/exp3.cpp
jubatus/core/bandit/exp3.hpp
jubatus/core/bandit/softmax.cpp
jubatus/core/bandit/softmax.hpp
jubatus/core/bandit/ts.cpp
jubatus/core/bandit/ts.hpp
jubatus/core/bandit/ucb1.cpp
jubatus/core/bandit/ucb1.hpp

fix #363 
I have added seed option to e-greedy, softmax, exp3, ts.

add seed option to bandit algorithms

---

jubatus/core/anomaly/anomaly_base.hpp
jubatus/core/anomaly/anomaly_base_test.cpp
jubatus/core/anomaly/light_lof.cpp
jubatus/core/anomaly/light_lof.hpp
jubatus/core/anomaly/light_lof_test.cpp
jubatus/core/anomaly/lof.cpp
jubatus/core/anomaly/lof.hpp
jubatus/core/anomaly/lof_storage.cpp
jubatus/core/anomaly/lof_storage.hpp
jubatus/core/anomaly/lof_storage_test.cpp
jubatus/core/driver/anomaly.cpp
jubatus/core/driver/anomaly.hpp
jubatus/core/driver/anomaly_test.cpp
jubatus/core/nearest_neighbor/nearest_neighbor_base.cpp
jubatus/core/nearest_neighbor/nearest_neighbor_base.hpp
jubatus/core/nearest_neighbor/nearest_neighbor_test.cpp

Fixes https://github.com/jubatus/jubatus/issues/1194

Add some information to get_status of anomaly

---

jubatus/core/nearest_neighbor/bit_vector_ranking.cpp
jubatus/core/nearest_neighbor/bit_vector_ranking.hpp
jubatus/core/nearest_neighbor/euclid_lsh.cpp
jubatus/core/nearest_neighbor/nearest_neighbor_test.cpp

Fixes floting point exception in NN when data is empty

---

jubatus/util/text/json/base.h
jubatus/util/text/json_test.cpp

This PR implements equality operator for JSON objects.

Implement equality operator for json object

---

wscript

Refs https://github.com/jubatus/jubatus_core/issues/378

add --disable-fmv configure option

---

jubatus/core/fv_converter/wscript

Fix #376.
This is a regression introduced in Jubatus 1.0.1:
Refs https://github.com/jubatus/jubatus/pull/1122 and https://github.com/jubatus/jubatus_core/pull/338/files#diff-d72d7cf04ce10051c2167b962c22e45bR26

fix wscript to pass build on FreeBSD (fix #376)

---

jubatus/core/driver/recommender.cpp
jubatus/core/driver/recommender.hpp
jubatus/core/driver/recommender_test.cpp

Refs. https://github.com/jubatus/jubatus/issues/1100

 Implement similar_row_from_*_and_{score,rate} to recommender

---

jubatus/core/anomaly/anomaly_base.hpp
jubatus/core/anomaly/anomaly_base_test.cpp
jubatus/core/anomaly/light_lof.cpp
jubatus/core/anomaly/light_lof.hpp
jubatus/core/anomaly/light_lof_test.cpp
jubatus/core/anomaly/lof.cpp
jubatus/core/anomaly/lof.hpp
jubatus/core/anomaly/lof_storage.cpp
jubatus/core/anomaly/lof_storage.hpp
jubatus/core/anomaly/lof_test.cpp
jubatus/core/driver/anomaly.cpp
jubatus/core/driver/anomaly.hpp

fix #360 
I have added add_bulk API to anomaly_base.
And implemented update_bulk in lof and lof_storage and set_bulk in light_lof.
This API returns the ids which are successfully updated by the API.

add add_bulk api

---

jubatus/core/anomaly/anomaly_base.hpp
jubatus/core/anomaly/anomaly_base_test.cpp
jubatus/core/anomaly/light_lof.cpp
jubatus/core/anomaly/light_lof.hpp
jubatus/core/anomaly/lof.cpp
jubatus/core/anomaly/lof.hpp
jubatus/core/anomaly/lof_storage.cpp
jubatus/core/anomaly/lof_storage.hpp
jubatus/core/driver/anomaly.cpp
jubatus/core/driver/anomaly.hpp

use reference in add_bulk
